### ISSUE TITLE
Creating default object from empty value

### ISSUE THREAD

**Issue by dungphanxuan** [kartik-v/yii2-tree-manager#12]
Hello, i flow your instruction and have error : Creating default object from empty value. I think that tbl_tree is empty. And how i insert data to

**Comment by kartik-v** [comment]
See related issue #11.

Let know, what's different in your case, because I cannot replicate this issue.

**Comment by adiramardiani** [comment]
I also experienced it, but I guess it was not because of his empty table, but there may be a configuration or something is wrong
I in this line
```php
$node->$iconTypeAttribute = ArrayHelper::getValue($this->iconEditSettings, 'type', self::ICON_CSS);
```

![download](https://cloud.githubusercontent.com/assets/8703419/6664122/b82556a6-cbff-11e4-8e02-6649e8d70e59.png)

**Comment by dungphanxuan** [comment]
Hi @kartik-v . i have same error . And i try to install some data. Then it run! thank!

 if (Tree::find()->count() == 0) {
            $home = new Tree(['name' => 'Home']);
            $home->makeRoot();
            $site1 = new Tree(['name' => 'Site 1']);
            $site1->prependTo($home);
 }
But, the widget run when i change root node id  to 1 .

Example. when i call makeRoot method. Data root will insert to db. But id now is separate 1, app run with error "Creating default object from empty value". So i change id root to 1 and app run!

**Comment by kartik-v** [comment]
@adiramardiani your issue should not happen unless you have overridden the module `dataStructure` to remove the `iconTypeAttribute` property or its setting.

@dungphanxuan  - you do not need to initialize the data in the table and can ALSO do this by using **ADD NEW ROOT** button from the widget as posted in [my screenshot in issue #11](https://github.com/kartik-v/yii2-tree-manager/issues/11#issuecomment-80863576). 

In your case of value 1 for the root... note by default the TreeView widget uses the `displayValue` property to select a tree node ON init. [Read docs](http://demos.krajee.com/tree-manager). This defaults to `1`. But you may choose to override and set to what you want on init.

**Comment by adiramardiani** [comment]
Sorry I still do not understand to remove the ```iconTypeAttribute``` property or its setting.
I configure in module :
```php
'treemanager' =>  [
			'class' => '\kartik\tree\Module',
			// other module settings, refer detailed documentation
			'dataStructure'=>[
				'keyAttribute' => 'id',
				'nameAttribute' => 'name',
				'iconAttribute' => 'icon',
				'iconEditSettings' =>1
			],
			
		]
```

And in my view
```php
use kartik\tree\TreeView;

echo TreeView::widget([
    // single query fetch to render the tree
    'query' => Product::find()->addOrderBy('root, lft'), 
    'headingOptions' => ['label' => 'Categories'],
    'fontAwesome' => false,     // optional
    'isAdmin' => false,         // optional (toggle to enable admin mode)
    'displayValue' => 1,        // initial display value
    'softDelete' => true,       // defaults to true
    'cacheSettings' => [        
        'enableCache' => true   // defaults to true
    ]
]);
```

Sorry for my stupid question, what is wrong in my configuration so as not to throw :
```
Creating default object from empty value
```

Thanks

**Comment by kartik-v** [comment]
You have a wrong configuration setting, that's why you are facing the error. There is no property  called `iconEditSettings` in data structure - its `iconTypeAttribute`. This attribute is mandatory. You cannot remove it.

Note `iconEditSettings` defaults to:

```php
    [
    'keyAttribute' => 'id',
    'nameAttribute' => 'name',
    'iconAttribute' => 'icon',
    'iconTypeAttribute' => 'icon_type'
    ]
```

Please [read module setup documentation](http://demos.krajee.com/tree-manager#module).

**Comment by kartik-v** [comment]
You have a wrong configuration setting, that's why you are facing the error. There is no property  called `iconEditSettings` in data structure - its `iconTypeAttribute`. This attribute is mandatory. You cannot remove it.

**Please [read module setup documentation](http://demos.krajee.com/tree-manager#module).**

Note `treeStructure` defaults to:

```php
 [
    'keyAttribute' => 'id',
    'nameAttribute' => 'name',
    'iconAttribute' => 'icon',
    'iconTypeAttribute' => 'icon_type'
]
```

**Comment by kartik-v** [comment]
You have a wrong configuration setting, that's why you are facing the error. 

There is no property  called `iconEditSettings` in module `dataStructure` - the one missing above is `iconTypeAttribute`. This attribute is mandatory. You cannot remove it. 

**Please [read module setup documentation](http://demos.krajee.com/tree-manager#module).**

You do not need to tamper OR SET the `treeStructure` or `dataStructure` in module if you are using the default table provided with the extension. You need to change it ONLY if you change the field names for the attributes mentioned. DO NOT add any other entries to the `treeStructure` or `dataStructure` arrays. It will not be read OR used and instead will throw errors.

 You can choose to add your own fields if you need separately to the table -  and read it separately through your model.
Note `dataStructure` defaults to:

```php
 [
    'keyAttribute' => 'id',
    'nameAttribute' => 'name',
    'iconAttribute' => 'icon',
    'iconTypeAttribute' => 'icon_type'
]
```

**Comment by adiramardiani** [comment]
I'm so sorry, with my last configuration above
Hufft, but i change with your configuration above still throw error, is [E_STRICT](http://stackoverflow.com/questions/8900701/creating-default-object-from-empty-value-in-php) issue ?
my php version is 5.4.22
