### ISSUE TITLE
Problem with remove node: Undefined variable: keyAttribute

### ISSUE THREAD

**Issue by neelamharne21** [kartik-v/yii2-tree-manager#185]
when i try to delete node it shows error msg : Undefined variable: keyAttribute

**Comment by moltam** [comment]
@strtob The problem for me was that the model generated by Gii overwrited the `rules()` method. Just remove the `rules()` method from your generated model, and leave the validation for the extension.

If you generate the model, the following rules are generated: 

```php
public function rules()
{
    return [
        [['root', 'lft', 'rgt', 'lvl', 'icon_type', 'active', 'selected', 'disabled', 'readonly', 'visible', 'collapsed', 'movable_u', 'movable_d', 'movable_l', 'movable_r', 'removable', 'removable_all'], 'integer'],
        [['name'], 'required'],
        [['name'], 'string', 'max' => 60],
        [['icon'], 'string', 'max' => 255],
    ];
}
```

The `TreeTrait` treats some of these integer fields as boolean (for example: `$child->active = true;`), and the validation will fail because of the integer rule. So removing the unnecessary `rules()` method from your model solves the problem.

@kartik-v I think there is indeed an undefined variable in the [TreeTrait](https://github.com/kartik-v/yii2-tree-manager/blob/2f91ac6508b2558b8f6cff248eeba875854c8f94/src/models/TreeTrait.php#L333-L342). There is an extract before this (`extract($module->treeStructure);`), but the `keyAttribute`, and `nameAttribute` is declared in the `$module->dataStructure` array.

**Comment by kartik-v** [comment]
This is resolved via the fix above.
